services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
