version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=we
      - POSTGRES_PASSWORD=swe24
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8091:8080"

  frontend:
    build:
      context: ./src/main/terminplanung-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - postgres
    environment:
      - VITE_HOST=0.0.0.0

volumes:
  postgres_data:
